name: CI
on:
  push: 
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout 
        uses: actions/checkout@master 
        with: # 参数
          submodules: true
      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2.2.2
        with:
          hugo-version: '0.74.2'
          extended: true
      - name: Build
        run: hugo --minify --buildDrafts
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v2.5.1
        env:
          ACTIONS_DEPLOY_KEY: ${{ secrets.ACTIONS_DEPLOY_KEY }}
          EXTERNAL_REPOSITORY: chuxiuhong/chuxiuhong.github.io
          PUBLISH_BRANCH: master
          PUBLISH_DIR: ./public